In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
data_root = '/home/dhruvagarwal/projects/MitoSpace4D/runs/lightning_logs/resnetbilstm_encoded_normal/embeddings/'

print("Loading data...")
emb = np.load(os.path.join(data_root, "embeddings.npy"))         # (34145, 20, 2048)
labels = np.load(os.path.join(data_root, "labels.npy"))     
img_paths = np.load(os.path.join(data_root, "image_file_paths.npy"))

Loading data...

In [3]:
df = pd.DataFrame({
    'img_path': img_paths,
    'label': labels,
    'embedding': list(emb)
})

In [4]:
# sort by img_path
df = df.sort_values(by='img_path').reset_index(drop=True)
df.head(10)

,img_path,label,embedding
0,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[-0.0038727722, -0.070330165, 0.008922026, -0..."
1,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[-0.0040684817, -0.037948124, 0.013946517, -0..."
2,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.017555412, -0.0596712, 0.014921052, -0.012..."
3,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.01739778, -0.07292732, 0.02202934, -0.0045..."
4,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.041184615, -0.060628336, -0.0030301332, -0..."
5,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.014436673, -0.060744148, 0.0029845415, -0...."
6,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.035251286, -0.050978687, -0.013325442, -0...."
7,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.02913236, -0.03861627, -0.016597386, -0.02..."
8,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[-0.0041771643, -0.05335753, 0.009797752, -0...."
9,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.025946956, -0.011530736, -0.031605076, -0...."

In [5]:
# add pseudo region_id to each row based on img_path: for every label, divide the rows into groups of 100
df['region_id'] = df.groupby('label').cumcount() // 100
df.head(10)

,img_path,label,embedding,region_id
0,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[-0.0038727722, -0.070330165, 0.008922026, -0...",0
1,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[-0.0040684817, -0.037948124, 0.013946517, -0...",0
2,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.017555412, -0.0596712, 0.014921052, -0.012...",0
3,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.01739778, -0.07292732, 0.02202934, -0.0045...",0
4,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.041184615, -0.060628336, -0.0030301332, -0...",0
5,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.014436673, -0.060744148, 0.0029845415, -0....",0
6,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.035251286, -0.050978687, -0.013325442, -0....",0
7,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.02913236, -0.03861627, -0.016597386, -0.02...",0
8,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[-0.0041771643, -0.05335753, 0.009797752, -0....",0
9,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[[0.025946956, -0.011530736, -0.031605076, -0....",0

In [6]:
# now expand by timepoints
df_expanded = df.explode('embedding').reset_index(drop=True)
df_expanded.head(10)

,img_path,label,embedding,region_id
0,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.0038727722, -0.070330165, 0.008922026, -0....",0
1,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.002504793, -0.06880365, 0.008194874, -0.01...",0
2,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.0013903215, -0.06785194, 0.0075677256, -0....",0
3,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.00019644758, -0.06705973, 0.008143752, -0.0...",0
4,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0005769702, -0.064653784, 0.008935568, -0.0...",0
5,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.001605081, -0.06346772, 0.009552148, -0.017...",0
6,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0020066763, -0.062307063, 0.010214856, -0.0...",0
7,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.001734154, -0.061929245, 0.010620148, -0.01...",0
8,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0013759941, -0.062204957, 0.010946776, -0.0...",0
9,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0010890877, -0.06247866, 0.0112591935, -0.0...",0

In [7]:
# add timepoint column
df_expanded['timepoint'] = df_expanded.groupby('img_path').cumcount()
df_expanded.head(10)

,img_path,label,embedding,region_id,timepoint
0,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.0038727722, -0.070330165, 0.008922026, -0....",0,0
1,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.002504793, -0.06880365, 0.008194874, -0.01...",0,1
2,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.0013903215, -0.06785194, 0.0075677256, -0....",0,2
3,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.00019644758, -0.06705973, 0.008143752, -0.0...",0,3
4,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0005769702, -0.064653784, 0.008935568, -0.0...",0,4
5,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.001605081, -0.06346772, 0.009552148, -0.017...",0,5
6,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0020066763, -0.062307063, 0.010214856, -0.0...",0,6
7,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.001734154, -0.061929245, 0.010620148, -0.01...",0,7
8,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0013759941, -0.062204957, 0.010946776, -0.0...",0,8
9,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0010890877, -0.06247866, 0.0112591935, -0.0...",0,9

In [8]:
# now add a actual time column based on region_id and timepoint
df_expanded['time'] = df_expanded['region_id'] * 20 + df_expanded['timepoint']
df_expanded.head(10)

,img_path,label,embedding,region_id,timepoint,time
0,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.0038727722, -0.070330165, 0.008922026, -0....",0,0,0
1,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.002504793, -0.06880365, 0.008194874, -0.01...",0,1,1
2,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.0013903215, -0.06785194, 0.0075677256, -0....",0,2,2
3,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.00019644758, -0.06705973, 0.008143752, -0.0...",0,3,3
4,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0005769702, -0.064653784, 0.008935568, -0.0...",0,4,4
5,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.001605081, -0.06346772, 0.009552148, -0.017...",0,5,5
6,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0020066763, -0.062307063, 0.010214856, -0.0...",0,6,6
7,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.001734154, -0.061929245, 0.010620148, -0.01...",0,7,7
8,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0013759941, -0.062204957, 0.010946776, -0.0...",0,8,8
9,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0010890877, -0.06247866, 0.0112591935, -0.0...",0,9,9

In [9]:
control_df = df_expanded[df_expanded['label'] == 0].reset_index(drop=True)
len(control_df)

26360

In [10]:
drug_labels_dict = {}
label_drug_dict = {}
with open(f"/home/dhruvagarwal/projects/MitoSpace4D/extraction_utils/drugs_to_labels.txt", 'r') as f:
    for line in f:
        folder, drug, label = line.split()
        drug_labels_dict[drug] = int(label)
        label_drug_dict[int(label)] = drug

In [11]:
# map labels to drug names
df_expanded['drug'] = df_expanded['label'].map(label_drug_dict)
df_expanded.head(10)

,img_path,label,embedding,region_id,timepoint,time,drug
0,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.0038727722, -0.070330165, 0.008922026, -0....",0,0,0,control
1,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.002504793, -0.06880365, 0.008194874, -0.01...",0,1,1,control
2,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[-0.0013903215, -0.06785194, 0.0075677256, -0....",0,2,2,control
3,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.00019644758, -0.06705973, 0.008143752, -0.0...",0,3,3,control
4,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0005769702, -0.064653784, 0.008935568, -0.0...",0,4,4,control
5,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.001605081, -0.06346772, 0.009552148, -0.017...",0,5,5,control
6,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0020066763, -0.062307063, 0.010214856, -0.0...",0,6,6,control
7,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.001734154, -0.061929245, 0.010620148, -0.01...",0,7,7,control
8,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0013759941, -0.062204957, 0.010946776, -0.0...",0,8,8,control
9,/media/dhruvagarwal/easystore/MitoSpace4D/data...,0,"[0.0010890877, -0.06247866, 0.0112591935, -0.0...",0,9,9,control

In [12]:
df_expanded.to_parquet('expanded_embeddings_with_time.parquet', index=False)

In [13]:
len(df_expanded)

682900